### ISSUE TITLE
already packages that do this

### ISSUE THREAD

**Issue by tracker1** [Atishay96/utils-deep-clone#1]
Just an FYI... I wrote `safe-clone-deep` there's also `fclone`

**Comment by Atishay96** [comment]
Oh, thanks I wasn’t aware of those. I’ll have a look at both of them. :)

**Comment by tracker1** [comment]
@Atishay96 you could probably just replace your helpers `deepCloneJSON` method with `fclone` ...

Aside: as a matter of course you aren't deep cloning JSON, JSON is always a string, you are deep cloning an object.  The only place you should use JSON as a term or part of a method name, is if you are actually interacting with a String that contains JSON either inputting JSON our outputting it, otherwise it's just an object or primitive value and probably superfluous.
